### ISSUE TITLE
改如何调用update事件

### ISSUE THREAD

**Issue by fumingchen** [lx544690189/vue-gemini-scrollbar#1]
由于我的组件需要通过v-for渲染出来，但是，发现滚动条的宽度和高度都为17px，猜测，我需要滚动的内容还没渲染出来，滚动条就已经生成了，所以我想手动调用update事件

**Comment by lx544690189** [comment]
能提供代码示例么，正常来说说组件内部触发渲染，会重新计算滚动条的。你或者在@ready方法里获取实例对象，用法参见第四个demo
