### ISSUE TITLE
不能引入 差ts的声明文件

### ISSUE THREAD

**Issue by allen2001** [lx544690189/vue-gemini-scrollbar#4]
无法找到模块“vue-gemini-scrollbar”的声明文件。“f:/workspace/qccqfront/node_modules/vue-gemini-scrollbar/dist/vue-gemini-scrollbar.js”隐式拥有 "any" 类型。
  Try `npm install @types/vue-gemini-scrollbar` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-gemini-scrollbar';`ts(7016)

vscode的错误提示

**Comment by lx544690189** [comment]
如果要使用typescript，可以在自己项目中加上ts的申明文件
